✨ Fix #72: workflows/publish_to_pypi.yml: Improved error handling in publishing process.

diff --git a/.github/workflows/publish_to_pypi.yml b/.github/workflows/publish_to_pypi.yml
--- a/.github/workflows/publish_to_pypi.yml
+++ b/.github/workflows/publish_to_pypi.yml
@@ -31,6 +31,8 @@ jobs:
               run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
               
             - name: Build and Publish
-              run: poetry publish --build
+              run: |
+                  set -e  # Exit immediately on non-zero exit-code.
+                  poetry publish --build || { echo "Publishing to PyPi failed!"; exit 1; }
               
             
